namespace: dev

services:
  config-server:
    image:
      tag: d5d3fb9

  discovery-server:
    image:
      tag: d5d3fb9

  admin-server:
    image:
      tag: d5d3fb9

  customers-service:
    image:
      tag: 5bfa0b4

  visits-service:
    image:
      tag: deeef46

  vets-service:
    image:
      tag: de36828

  genai-service:
    image:
      tag: d5d3fb9

  api-gateway:
    image:
      tag: a3f5cdd

  grafana:
    image:
      tag: a3f5cdd

  prometheus:
    image:
      tag: a3f5cdd

  loki:
    image:
      tag: a3f5cdd
