namespace: dev

services:
  config-server:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest

  admin-server:
    image:
      tag: latest

  customers-service:
    image:
      tag: 122e952

  visits-service:
    image:
      tag: 122e952

  vets-service:
    image:
      tag: 122e952

  genai-service:
    image:
      tag: latest

  api-gateway:
    image:
      tag: 122e952
