namespace: prod

services:
  config-server:
    image:
      tag: release-v1.0

  discovery-server:
    image:
      tag: release-v1.0

  admin-server:
    image:
      tag: release-v1.0

  customers-service:
    image:
      tag: release-v1.0

  visits-service:
    image:
      tag: release-v1.0

  vets-service:
    image:
      tag: release-v1.0

  genai-service:
    image:
      tag: release-v1.0

  api-gateway:
    image:
      tag: release-v1.0
