apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-dev1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: 'https://github.com/kiin21/petclinic-manifests.git' # Replace with your Git repository URL
    targetRevision: HEAD                                      # the branch/tag/commit hash to deploy
    path: .        # Path to the Helm chart in the repository
    helm:
      valueFiles:
        - values.yaml                   # Default values
        - environments/preview-test-dev1-values.yaml  # Dev-specific overrides

  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes cluster API server
    namespace: preview-test-dev1                          # Namespace for the dev environment

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true