apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-clinic-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/kiin21/petclinic-gitops.git' # Replace with your Git repository URL
    targetRevision: main                                      # the branch/tag/commit hash to deploy
    path: .        # Path to the Helm chart in the repository
    helm:
      valueFiles:
        - values.yaml                   # Default values
        - environments/staging-values.yaml  # Staging-specific overrides

  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes cluster API server
    namespace: Staging                          # Namespace for the staging environment

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true